FROM python:3.6.5-alpine3.7

ENV PYTHONUNBUFFERED 1


RUN apk add --update git nano gcc musl-dev openrc \
    && rm -f /var/cache/apk/* \
    && pip install -U pip \
    && pip install flask \
    && pip install requests \
    && pip install flask-restful \
    && pip install gevent \
    && git clone https://github.com/jameskozlowski/randomnumberapi.git /home/randomnumberapi

EXPOSE 8080
CMD ["python3 /home/randomnumberapi/api.py"]
